# This file was automatically generated by alf
# https://github.com/dannyben/alf

unalias update 1>/dev/null 2>&1
update() {
  sudo apt update;sudo apt upgrade -y "$@"
}

unalias goto 1>/dev/null 2>&1
goto() {
  case "$1" in
    pec)
      shift
      cd ~/Documents/Bridge/Code/pec "$@"
      ;;
    pec-assinador)
      shift
      cd ~/Documents/Bridge/Code/pec-assinador "$@"
      ;;
    *)
      cd "$@"
      ;;
  esac
}

unalias automvn 1>/dev/null 2>&1
automvn() {
  case "$1" in
    build)
      shift
      mvn -T 1C clean install -DskipTest -Dmaven.test.skip -Dmaven.javadoc.skip=true "$@"
      ;;
    run)
      shift
      mvn spring-boot:run -Dspring.profiles.active=dev,dev-postgres -Dbridge.flags.experimental=true "$@"
      ;;
    *)
      mvn "$@"
      ;;
  esac
}

unalias notes 1>/dev/null 2>&1
notes() {
  nvim ~/Documents/Geral/notes.txt "$@"
}

# Completions
if command -v complete &> /dev/null ; then
  complete -W "pec pec-assinador" goto
  complete -W "build run" automvn
fi
