hl.on("hyprland.start", function()
	hl.exec_cmd("hypridle")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprlock")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("openrgb --noautoconnect --profile White.orp")
	hl.exec_cmd("easyeffects --hide-window")
end)
